### ISSUE TITLE
Error after deleting a user

### ISSUE THREAD

**Issue by funkycram** [humhub/mail#343] opened 2023-08-09 11:07 UTC
Error log:

```
yii\base\ErrorException: Attempt to read property "users" on null in
/var/www/humhub/protected/modules/mail/models/AbstractMessageEntry.php:147
Stack trace:
#0
/var/www/humhub/protected/modules/mail/models/AbstractMessageEntry.php(147):
yii\base\ErrorHandler->handleError()
#1
/var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(770):
humhub\modules\mail\models\AbstractMessageEntry->afterDelete()
#2
/var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724):
yii\db\ActiveRecord->deleteInternal()
#3
/var/www/humhub/protected/modules/mail/Events.php(102):
yii\db\ActiveRecord->delete()
#4 [internal function]: humhub\modules\mail\Events::onUserDelete()
#5
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312):
call_user_func()
#6
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642):
yii\base\Event::trigger()
#7
/var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1025):
yii\base\Component->trigger()
#8
/var/www/humhub/protected/humhub/modules/user/models/User.php(473):
yii\db\BaseActiveRecord->beforeDelete()
#9
/var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(754):
humhub\modules\user\models\User->beforeDelete()
#10
/var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(724):
yii\db\ActiveRecord->deleteInternal()
#11
/var/www/humhub/protected/humhub/modules/user/jobs/DeleteUser.php(49):
yii\db\ActiveRecord->delete()
#12
/var/www/humhub/protected/humhub/modules/queue/ActiveJob.php(33):
humhub\modules\user\jobs\DeleteUser->run()
#13
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246):
humhub\modules\queue\ActiveJob->execute()
#14
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162):
yii\queue\Queue->handleMessage()
#15
/var/www/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146):
yii\queue\cli\Queue->execute()
#16 [internal function]: yii\queue\cli\Command->actionExec()
#17
/var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array()
#18
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178):
yii\base\InlineAction->runWithParams()
#19
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180):
yii\base\Controller->runAction()
#20
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552):
yii\console\Controller->runAction()
#21
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180):
yii\base\Module->runAction()
#22
/var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147):
yii\console\Application->runAction()
#23
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384):
yii\console\Application->handleRequest()
#24 /var/www/humhub/protected/yii(29):
yii\base\Application->run()
#25 {main}
in
/var/www/humhub/protected/modules/mail/Events.php:117
in
/var/www/humhub/protected/humhub/modules/user/models/User.php:473
in
/var/www/humhub/protected/humhub/modules/user/jobs/DeleteUser.php:49
```

If think we should add `if ($this->message->users) { ...` in `AbstractMessageEntry::afterDelete()`: https://github.com/humhub/mail/blob/master/models/AbstractMessageEntry.php#L147

**Comment by yurabakhtin** [comment] 2023-08-09 17:23
> If think we should add `if ($this->message->users) { ...` in `AbstractMessageEntry::afterDelete()`: https://github.com/humhub/mail/blob/master/models/AbstractMessageEntry.php#L147

@funkycram Thanks for the detected error, but the error message tells about `$this->message === null`, I guess you have some Message Entry without linked Converstation, it looks like the Converstation was deleted but its Message Entry was not. I don't find how it is possible, something was broken in your DB.
In order to avoid such broken entries without correct linked converstation I decided to remove them on Integrity Check tool like this:

![mail_integrity_check](https://github.com/humhub/mail/assets/6995524/7d4856b0-88d5-4347-a1db-0b1ed4d65ef8)

@luke- Fixed in PR https://github.com/humhub/mail/pull/344.

**Closed** 2023-08-10 21:38 UTC
Labels: bug

**Comment by funkycram** [comment] 2023-08-15 14:18
Thanks @yurabakhtin . Not tested because I don't know how to reproduce.

**Comment by yurabakhtin** [comment] 2023-08-15 15:22
@funkycram I didn't find how to reproduce this too, I just manually edit my test DB to make one record in `message_entry` with column `message_id` = `NULL` or some id of not existing converstation like `1234567`.
