### ISSUE TITLE
Message Overview Panel Design 

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/mail#307] opened 2023-03-06 17:30 UTC
@yurabakhtin in order to put the design process of the mail module to an end we wanted to redesign the message overview panel. There are a view things that don't work well. 
i.eg.:
the message overview style that you reach through the envelop icon in the top nav bar doesn't match the message overview style inside the mail module.
![Screen Shot 2023-03-06 at 3 26 14 PM](https://user-images.githubusercontent.com/105652258/223142211-ea43f92f-38e7-478f-ad18-477e88faf044.png)

# Firstly: Please make the button "show all messages" react on hover:
![Screen Shot 2023-03-06 at 5 19 26 PM](https://user-images.githubusercontent.com/105652258/223183790-7e011767-dc38-44af-b337-53b5334bd31e.png)
**adapt this style for "show all notifications" panel (bell icon next to envelop icon**)

# Secondly: Please change the style of the messages panel:
![Screen Shot 2023-03-06 at 6 18 48 PM](https://user-images.githubusercontent.com/105652258/223184411-fba4b5fe-16b1-4a69-ae39-f1ea38c3fb32.png)

## Please make panel hight 100%
![Screen Shot 2023-03-06 at 6 25 27 PM](https://user-images.githubusercontent.com/105652258/223185792-b9708be9-20a5-49a5-89cf-3e5480da125d.png)

**Comment by yurabakhtin** [comment] 2023-03-07 14:23
@Eladnarlea @luke- Commit https://github.com/humhub/mail/pull/283/commits/5bc2d232cdef06706d76e8bb08ec24a2ff45748a:

![mail](https://user-images.githubusercontent.com/6995524/223450043-9ca29b97-f7ba-4a8b-9eff-83f56a64c8df.png)

**Comment by luke-** [comment] 2023-03-07 14:25
@Eladnarlea Updated

**Comment by Eladnarlea** [comment] 2023-03-07 16:57
@yurabakhtin please take a closer look at point **3. MESSAGE PREVIEW**

**Comment by luke-** [comment] 2023-03-07 17:00
@yurabakhtin Can you please also take a look into this: 
![image](https://user-images.githubusercontent.com/4736168/223494160-58071c0a-dd1f-4aa0-a8a5-7c03b65250d9.png)
For some reason the "scroll to bottom" icon not correctly disappears

**Comment by yurabakhtin** [comment] 2023-03-08 07:21
@Eladnarlea 

> please take a closer look at point **3. MESSAGE PREVIEW** (colors, size and read/unread behavior)

Commit https://github.com/humhub/mail/pull/283/commits/b874ea33cb4aca6021a372a239b7010ca00ba667:

![mail-styles](https://user-images.githubusercontent.com/6995524/223647478-70527a36-a87b-401c-98c3-3cffe44b6804.png)

**Comment by yurabakhtin** [comment] 2023-03-08 07:48
@luke- 

> Can you please also take a look into this: ![image](https://user-images.githubusercontent.com/4736168/223494160-58071c0a-dd1f-4aa0-a8a5-7c03b65250d9.png) For some reason the "scroll to bottom" icon not correctly disappears

Could you show me how to reproduce the issue because I cannot find it on my side:

https://user-images.githubusercontent.com/6995524/223652586-9f6002b2-f796-49d2-8ed9-7e4958eaf9e8.mp4

**Comment by Eladnarlea** [comment] 2023-03-08 08:48
> @Eladnarlea
> 
> > please take a closer look at point **3. MESSAGE PREVIEW** (colors, size and read/unread behavior)
> 
> Commit [b874ea3](https://github.com/humhub/mail/commit/b874ea33cb4aca6021a372a239b7010ca00ba667):
> 
> ![mail-styles](https://user-images.githubusercontent.com/6995524/223647478-70527a36-a87b-401c-98c3-3cffe44b6804.png)

@yurabakhtin looking good so far, I will let you know as soon as my network is updated :)

**Comment by Eladnarlea** [comment] 2023-03-08 12:02
@yurabakhtin one thing: The "Conversation-Header" inside the mail module is background-color: grey. Please make that white- thank you! :)

**Comment by yurabakhtin** [comment] 2023-03-08 12:41
@Eladnarlea oh yes my mistake, fixed in next commit https://github.com/humhub/mail/pull/283/commits/aab8698e90e87708e94376763a73473da56f009e.

![header](https://user-images.githubusercontent.com/6995524/223715924-8d6f2789-b117-491f-9ebc-d61f68ee7e3d.png)

**Comment by Eladnarlea** [comment] 2023-03-13 10:49
@yurabakhtin could you please take a look into this: 

> **adapt this style for "show all notifications" panel (bell icon next to envelop icon**)

You did the hover right on the mail preview, please adapt it to the notification button, too! :)

**Comment by luke-** [comment] 2023-03-13 14:36
@yurabakhtin Please see: 

https://user-images.githubusercontent.com/4736168/224733245-d9ccd836-c8a4-4cd7-96ba-c85d127855f8.mp4

On my tests after a while the indicator was always hidden.

**Comment by yurabakhtin** [comment] 2023-03-14 06:44
@Eladnarlea 

> @yurabakhtin could you please take a look into this:
> 
> > **adapt this style for "show all notifications" panel (bell icon next to envelop icon**)
> 
> You did the hover right on the mail preview, please adapt it to the notification button, too! :)

Sorry, but I cannot understand what to fix. Could you please show me what is wrong?

![mail-question](https://user-images.githubusercontent.com/6995524/224917462-fbb19f35-87aa-48df-9ad3-2ba658693723.png)

**Comment by Eladnarlea** [comment] 2023-03-14 07:06
<img width="392" alt="Screen Shot 2023-03-14 at 8 04 40 AM" src="https://user-images.githubusercontent.com/105652258/224921884-a8d338f8-c665-4c74-8127-737213306b00.png">

@yurabakhtin please adapt the hover motion to the bell icon button, too! I hope now it is more understandable.

**Comment by yurabakhtin** [comment] 2023-03-14 08:21
@Eladnarlea Thanks for the screenshot, I thought we tell only about the mail module here.

@luke- I have done the style changes in core PR https://github.com/humhub/humhub/pull/6167, and removed the same code from the mail module https://github.com/humhub/mail/pull/311.

**Comment by yurabakhtin** [comment] 2023-03-14 09:31
> @yurabakhtin Please see:
> 
> On my tests after a while the indicator was always hidden.

@luke- Fixed in PR https://github.com/humhub/mail/pull/312.

**Comment by luke-** [comment] 2023-03-14 13:21
@yurabakhtin Can you please check the PR comment with the hardcoded colors?

**Comment by yurabakhtin** [comment] 2023-03-15 04:36
@luke- Fixed in commit https://github.com/humhub/humhub/pull/6167/commits/bf3d3655e1a7d088bf733d9a8230516988fc77ef.

**Comment by luke-** [comment] 2023-03-15 08:47
@yurabakhtin thanks it's merged

**Closed** 2023-03-15 09:29 UTC
Labels: enhancement
