### ISSUE TITLE
Conversation removed, if only one participant left.

### ISSUE THREAD

**Issue by gigabytedevelopers** [humhub/mail#112] opened 2017-01-02 03:32 UTC
There is this bug on humhub in the mail module (a very huge bug). If User A and User B is chatting, and User A decides to exit the conversation, the conversation clears on both User A and User B's accounts instead of only on User A's account (the person who exitted the conversation).

**Comment by Felli** [comment] 2017-01-03 02:05
Duplicate of #111

**Comment by binarynos** [comment] 2017-01-04 06:56
Not exactly a duplicate I think

**Comment by jcmarchi** [comment] 2019-05-18 23:58
Any status on this? Not only is bad to lose the conversation from the perspective of the person that didn't leave it but also not being able to get back to it. Conversations allow attachments and many other interactions and some may be summarily important for everyone, even the ones who left it. It should have been a manner (an archived screen or old conversations tab) so people may retain the conversations up to the point when they left it, and also even if it is closed or archived.

The messaging is a great feature, well designed, highly important. However, the "leave it" button make it fragile and dangerous. Almost feel like either disabling it or changing the code to remove the "leave" button altogether.

A "fix" would be much nicer, of course. ;) Even better if a "history" or "archived items tab" is implemented.

**Closed** 2021-12-06 10:11 UTC
Labels: bug
